version: '3.3'

services:
  jenkins:
    build: #TODO: Once plugin installation is handled through c-as-c this can be removed and replaced with 'image'.
      context: ./jenkins-image
    ports:
      - 8888:8080
      - 55555:55555
    volumes:
      - jenkins_home:C:/ProgramData/Jenkins/JenkinsHome
      - \\.\pipe\docker_engine:\\.\pipe\docker_engine
      - ./casc_configs:C:/ProgramData/Jenkins/jcasc_configs
    secrets:
      - github  #Github username with password as an example.
      - adminpw  #Initial administrator user password.
    environment:
      - CASC_JENKINS_CONFIG=C:/ProgramData/Jenkins/jcasc_configs
secrets: #Be careful with newlines in your secrets, make sure to remove them before running docker-compose up.
  github:
    file: ./secrets/github
  adminpw:
    file: ./secrets/adminpw
volumes:
  jenkins_home:
